INSERT INTO problemtype (typeName) VALUES ('ACRYLIC PLATE');
INSERT INTO problemtype (typeName) VALUES ('AIR - CONDITIONER');
INSERT INTO problemtype (typeName) VALUES ('AUTO GATE BARRIER');
INSERT INTO problemtype (typeName) VALUES ('BED');
INSERT INTO problemtype (typeName) VALUES ('BOOK SHELF');
INSERT INTO problemtype (typeName) VALUES ('CABINET');
INSERT INTO problemtype (typeName) VALUES ('CEILING');
INSERT INTO problemtype (typeName) VALUES ('CHAIR');
INSERT INTO problemtype (typeName) VALUES ('CISTERN');
INSERT INTO problemtype (typeName) VALUES ('CLEANLINESS');
INSERT INTO problemtype (typeName) VALUES ('CLOGGED');
INSERT INTO problemtype (typeName) VALUES ('CLOTHES HANGER');
INSERT INTO problemtype (typeName) VALUES ('COUNTER SERVICE');
INSERT INTO problemtype (typeName) VALUES ('CURTAIN / BLIND');
INSERT INTO problemtype (typeName) VALUES ('DOOR');
INSERT INTO problemtype (typeName) VALUES ('DOOR LOCK');
INSERT INTO problemtype (typeName) VALUES ('DRAIN');
INSERT INTO problemtype (typeName) VALUES ('DRAWER / CUPBOARD');
INSERT INTO problemtype (typeName) VALUES ('DRYER');
INSERT INTO problemtype (typeName) VALUES ('ELECTRICAL TRIP');
INSERT INTO problemtype (typeName) VALUES ('EXHAUST FAN');
INSERT INTO problemtype (typeName) VALUES ('FAN');
INSERT INTO problemtype (typeName) VALUES ('FIRE ALARM PANEL');
INSERT INTO problemtype (typeName) VALUES ('FRIDGE');
INSERT INTO problemtype (typeName) VALUES ('GAS STOVE');
INSERT INTO problemtype (typeName) VALUES ('GRILL');
INSERT INTO problemtype (typeName) VALUES ('GUTTER');
INSERT INTO problemtype (typeName) VALUES ('INDUCTION COOKER');
INSERT INTO problemtype (typeName) VALUES ('KETTLE');
INSERT INTO problemtype (typeName) VALUES ('LAMP');
INSERT INTO problemtype (typeName) VALUES ('LANDSCAPE');
INSERT INTO problemtype (typeName) VALUES ('LEAKED');
INSERT INTO problemtype (typeName) VALUES ('LIFT');
INSERT INTO problemtype (typeName) VALUES ('LPG GAS');
INSERT INTO problemtype (typeName) VALUES ('MAIN HOLE');
INSERT INTO problemtype (typeName) VALUES ('MATTRESS');
INSERT INTO problemtype (typeName) VALUES ('MICB');
INSERT INTO problemtype (typeName) VALUES ('MICROWAVE');
INSERT INTO problemtype (typeName) VALUES ('MIRROR');
INSERT INTO problemtype (typeName) VALUES ('PA SYSTEM');
INSERT INTO problemtype (typeName) VALUES ('PEST CONTROL');
INSERT INTO problemtype (typeName) VALUES ('PIPING ');
INSERT INTO problemtype (typeName) VALUES ('ROAD');
INSERT INTO problemtype (typeName) VALUES ('ROOF');
INSERT INTO problemtype (typeName) VALUES ('SHOWER');
INSERT INTO problemtype (typeName) VALUES ('SIGNAGE');
INSERT INTO problemtype (typeName) VALUES ('INK');
INSERT INTO problemtype (typeName) VALUES ('SOCKET / PLUG');
INSERT INTO problemtype (typeName) VALUES ('TABLE');
INSERT INTO problemtype (typeName) VALUES ('TELEVISION');
INSERT INTO problemtype (typeName) VALUES ('TILES / FLOOR');
INSERT INTO problemtype (typeName) VALUES ('TOILET BOWL');
INSERT INTO problemtype (typeName) VALUES ('TOWEL HANGER');
INSERT INTO problemtype (typeName) VALUES ('WASHING MACHINE');
INSERT INTO problemtype (typeName) VALUES ('WATER BOILER');
INSERT INTO problemtype (typeName) VALUES ('WATER DISPENSER');
INSERT INTO problemtype (typeName) VALUES ('WATER HEATER');
INSERT INTO problemtype (typeName) VALUES ('WATER PRESSURE');
INSERT INTO problemtype (typeName) VALUES ('WATER PROOFING');
INSERT INTO problemtype (typeName) VALUES ('WATER SUPPLY');
INSERT INTO problemtype (typeName) VALUES ('WINDOW');